services:
  backend:
    build: ./back
    container_name: guitar-backend
    ports:
      - "8000:8000"
    env_file:
      - ./back/.env

  frontend:
    build: ./front
    container_name: guitar-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/recommend
    depends_on:
      - backend
